apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: cloud-native-platform
data:
  PORT: "8082"
  LOG_LEVEL: "info"
  READ_TIMEOUT: "15s"
  WRITE_TIMEOUT: "15s"
  REDIS_URL: "redis:6379"
  REDIS_PASSWORD: ""
  OTEL_EXPORTER_OTLP_ENDPOINT: "tempo:4318"
  PAYMENT_FAILURE_RATE: "0.0"
