apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: microservices-podmonitor
  namespace: cloud-native-platform
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
