apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: cloud-native-platform
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: inventory-service
